### ISSUE TITLE
Can't open dashboard

### ISSUE THREAD

**Issue by johny65** [jobrunr/example-microprofile#1]
I tried the example using Payara Micro instead of Liberty. All works fine except the dashboard, I can't find it deployed on any endpoint. I don't know what I'm missing.

Note that the example uses an outdated version of JobRunr (0.9.12). I change it to latest (1.2.0) but still the dashboard isn't working.

**Comment by rdehuyss** [comment]
Hi @johny65 , sorry for the late reply - I just found this issue.

Are you still struggling with it? If so, drop me a note and tag me - otherwise I'm not notified.

**Comment by johny65** [comment]
Hi @rdehuyss, I had forgotten about this. This is no more an issue, I could make it work, I'm closing this now. Thanks anyway. Great library 👍🏻 .

**Comment by rdehuyss** [comment]
Great, glad to hear! Feel free to star the JobRunr repo if you like it! ;-)
